services:
  mariadb:
    image: mariadb:10.9.2
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: food-reservation
    ports:
      - "3306:3306"
  app:
    image: oldrabbit736/food-reservation-app:temp
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JEP: ${JEP}
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/food-reservation
